services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: invite_manager_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./inviteManager:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: invite_manager_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./inviteManager:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: invite_manager_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: invite_manager_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: invite_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
